In [11]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Machine%20Learning%2BNLP%20Project%20Language%20Detection/language.csv")
print(data.head())


                                                Text  language
0  klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1  sebes joseph pereira thomas  på eng the jesuit...   Swedish
2  ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3  விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4  de spons behoort tot het geslacht haliclona en...     Dutch


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
data = ["Hello world", "Bonjour le monde", "Hola mundo"]
vectorized_data = vectorizer.fit_transform(data)
print(vectorized_data.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 0 0 0 0 1]
 [1 0 0 1 1 0 0]
 [0 0 1 0 0 1 0]]
['bonjour' 'hello' 'hola' 'le' 'monde' 'mundo' 'world']


In [6]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

emails = [
    "Hello, I saw your profile and would like to connect.",
    "Congratulations! You've won a lottery. Claim your prize now.",
    "Meeting scheduled for tomorrow at 10 AM.",
    "Get rich quick with this one simple trick!"
]

labels = [0, 1, 0, 1]  # 0 = not spam, 1 = spam

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.2, random_state=100
)

model = MultinomialNB()
model.fit(X_train, y_train)

print("Model trained successfully ✅")



Model trained successfully ✅


In [8]:
data


['Hello world', 'Bonjour le monde', 'Hola mundo']

In [12]:
data.isnull().sum()

Text        0
language    0
dtype: int64

In [13]:
data['language'].value_counts()

language
Estonian      1000
Swedish       1000
Thai          1000
Tamil         1000
Dutch         1000
Japanese      1000
Turkish       1000
Latin         1000
Urdu          1000
Indonesian    1000
Portugese     1000
French        1000
Chinese       1000
Korean        1000
Hindi         1000
Spanish       1000
Pushto        1000
Persian       1000
Romanian      1000
Russian       1000
English       1000
Arabic        1000
Name: count, dtype: int64

In [15]:
x = np.array(data['Text'])
y = np.array(data['language'])

print(x)

['klement gottwaldi surnukeha palsameeriti ning paigutati mausoleumi surnukeha oli aga liiga hilja ja oskamatult palsameeritud ning hakkas ilmutama lagunemise tundemärke  aastal viidi ta surnukeha mausoleumist ära ja kremeeriti zlíni linn kandis aastatel – nime gottwaldov ukrainas harkivi oblastis kandis zmiivi linn aastatel – nime gotvald'
 'sebes joseph pereira thomas  på eng the jesuits and the sino-russian treaty of nerchinsk  the diary of thomas pereira bibliotheca instituti historici s i --   rome libris '
 'ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เริ่มตั้งแต่ถนนสนามไชยถึงแม่น้ำเจ้าพระยาที่ถนนตก กรุงเทพมหานคร เป็นถนนรุ่นแรกที่ใช้เทคนิคการสร้างแบบตะวันตก ปัจจุบันผ่านพื้นที่เขตพระนคร เขตป้อมปราบศัตรูพ่าย เขตสัมพันธวงศ์ เขตบางรัก เขตสาทร และเขตบางคอแหลม'
 ...
 'con motivo de la celebración del septuagésimoquinto ° aniversario de la fundación del departamento en  guillermo ceballos espinosa presentó a la gobernación de caldas por encargo de su titular dilia estrada de gómez el h

In [16]:
cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=100)

In [17]:
model = MultinomialNB()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9618181818181818

In [22]:
user = input("Enter text to detect language: ")
data = cv.transform([user]).toarray()
output = model.predict(data)
print("Predicted language:", output)

Predicted language: ['Urdu']
